apiVersion: v1
kind: Service
metadata:
  name: {{ include "flask-api.fullname" . }}
  namespace: {{ .Values.namespace }} 
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 5001
      protocol: TCP
  selector:
    app: {{ include "flask-api.name" . }}
