name: CD

on:
  workflow_run:
    workflows: ["CI - Build, Lint, Test, and Push to ECR"]
    types:
      - completed

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/eks-cluster-management-role
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

      - name: Install yq
        run: |
          sudo snap install yq

      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

      - name: Deploy Helm Chart
        env:
          AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
        run: |
          NAMESPACE=$(yq eval '.namespace' "${{ github.workspace }}/_infra/values.yaml")
          RELEASE_NAME="python-flask-api" # this value can be dynamic
          helm upgrade --install "$RELEASE_NAME" "${{ github.workspace }}/_infra" \
            --namespace "$NAMESPACE" \
            --values "${{ github.workspace }}/_infra/values.yaml" \
            --set awsAccountId=${AWS_ACCOUNT_ID} \
            --set redeployTimestamp=$(date +%s) \
            --set imagePullPolicy=Always \
            --force
