name: CD

on:
  workflow_run:
    workflows: ["CI - Build, Lint, Test, and Push to ECR"]
    types:
      - completed

jobs:
 deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/bruno--setup-cd' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes context
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Install yq
      run: |
        sudo snap install yq

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Configure Kubernetes context
      env:
        KUBECONFIG: ${{ secrets.KUBE_CONFIG }}
      run: |
          echo "Creating .kube directory"
          mkdir -p $HOME/.kube  # Ensure .kube directory exists

          echo "Checking if .kube directory exists"
          ls -la $HOME/.kube  # List contents of .kube directory for debugging

          temp_config_file=$(mktemp)
          echo "$KUBECONFIG" > "$temp_config_file"
          echo "Temporary kube config created at $temp_config_file"

          mv "$temp_config_file" $HOME/.kube/config
          echo "Kube config moved to $HOME/.kube/config"

          # Use the context
          kubectl config use-context "${{ github.event.inputs.environment }}"

    - name: Deploy Helm Chart
      env:
        AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      run: |
        NAMESPACE=$(yq eval '.namespace' values.yaml)
        helm upgrade --install --generate-name ./_infra --namespace "$NAMESPACE" --values values.yaml --set awsAccountId=${AWS_ACCOUNT_ID}